spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    tomcat:
      connection-properties: "spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8"
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        connection:
          characterEncoding: UTF-8
        format_sql: true


  # Dados de conexão com o banco de dados PostgreSQL
  
  # datasource:
  #   url: jdbc:postgresql://comic-shop-api-db-1101/comic-shop?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=comic-shop-api-db-1101&user=D-Admin&password=pcZl0`rK}_(Zk)nX
  #   username: D-Admin
  #   password: pcZl0`rK}_(Zk)nX
  #   driver-class-name: org.postgresql.Driver
  # jpa:
  #   hibernate:
  #     ddl-auto: create-drop
  #   show-sql: false
  #   properties:
  #     hibernate:
  #       format_sql: true
  #   database: postgresql
  #   database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days