-- Inserção dos dados da revista "Senninha e Sua Turma #0"
INSERT INTO comic (title, synopsis, page_count, date, image, creator, price, rarity) VALUES ('Senninha e Sua Turma #0', 'E na estreia desta nova série, a primeira edição traz Senninha como o Pilotinho-Morcego, o defensor de Quatro Rodinhas City. Nesta aventura, o herói terá que enfrentar a falta de água que assola a cidade. Quem será o responsável por essa barbaridade? Completam a edição outras historinhas inéditas com toda a turma do Senninha, como Pedido Estranho, onde Senninha pede emprestado as bonecas das meninas da turma, deixando todas muito curiosas. O que será que vai acontecer com as bonecas das garotas? Este número traz também Segura, Peão!, onde Senninha e Johnny se tornam pilotos-peões e surpreendem as garotas do pedaço. Mas Braço Duro aparece para tentar acabar com a brincadeira.', 36, '03/11/2015', 'https://dvygmnfdru1l.cloudfront.net/Uo4mMNdEzTLp2FyTnBC2/0/6648a6ba-4371-4f59-bc17-b95a6f831f77', 'Mauricio de Sousa', 10.00, '1');

-- Inserção dos dados da revista "Senninha e Sua Turma #1"
INSERT INTO comic (title, synopsis, page_count, date, image, creator, price, rarity) VALUES ('Senninha e Sua Turma #1', 'E dizem por aí que, na edição número 1, Senninha está com um carro megadiferente, superpotente e cheio de truques. É a historinha “Carro Diferente”. Enquanto isso, Becão não pára de aprontar em “Não é Sapo”, paquerando as amigas do Senninha. Também tem a aventura “Chapeuzinhos Coloridos”, de dar inveja a qualquer Lobo Mau. Mas os personagens continuam com o pé no acelerador e outras histórias acontecem entre os passatempos cheios de desafios.', 36, '03/11/2015', 'https://dvygmnfdru1l.cloudfront.net/Uo4mMNdEzTLp2FyTnBC2/1/53d6a87a-6fd9-4099-a872-976daeffe532', 'Mauricio de Sousa', 15.00, '1');

-- Inserção dos dados da revista "Senninha e Sua Turma #2"
INSERT INTO comic (title, synopsis, page_count, date, image, creator, price, rarity) VALUES ('Senninha e Sua Turma #2', 'Nesta edição, Senninha se apaixona e a turma estranha o seu comportamento, temendo pelo que pode acontecer. É a aventura “Quando os corações viram gelatina”. Enquanto isso, os amigos Becão e Gigi vivem a história “O casalinho comilão”. E, além disso, a turma enfrenta um problema sério com a falta de espaço na estante de livros: tem de tudo, mas não tem onde colocar. O que fazer? É o “Detetive da Estante”. Senninha e os amigos precisam resolver esse mistério.', 36, '03/11/2015', 'https://dvygmnfdru1l.cloudfront.net/Uo4mMNdEzTLp2FyTnBC2/2/53d6a87a-6fd9-4099-a872-976daeffe532', 'Mauricio de Sousa', 20.00, '1');

-- Inserção dos dados da revista "Senninha e Sua Turma #3"
INSERT INTO comic (title, synopsis, page_count, date, image, creator, price, rarity) VALUES ('Senninha e Sua Turma #3', 'Senninha e a Turma estão na pista, mas não em corridas, e sim na vida. O professor de Educação Física, Hélio, dá um conselho importante: se você quer vencer, precisa se dedicar e ter disciplina. É a historinha “O conselho do professor Hélio”. Enquanto isso, Bóson, o nerd da turma, apronta das suas. Faz uma invenção maluca e quase bota tudo a perder. Mas, como sempre, a turma do Senninha dá um jeito de ajudar. Tudo isso e muito mais na edição “Piloto de Dedo”!', 36, '03/11/2015', 'https://dvygmnfdru1l.cloudfront.net/Uo4mMNdEzTLp2FyTnBC2/3/53d6a87a-6fd9-4099-a872-976daeffe532', 'Mauricio de Sousa', 25.00, '1');

-- Inserção dos dados da revista "Senninha e Sua Turma #4"
INSERT INTO comic (title, synopsis, page_count, date, image, creator, price, rarity) VALUES ('Senninha e Sua Turma #4', 'Nesta aventura, Senninha está muito animado. Ele vai receber uma visita muito especial: o piloto Rubinho Barrichello. O Rubinho vai fazer uma corrida com o carro dele e com o novo carro do Senninha. Os dois estão animados e prometem uma corrida emocionante. Será que o Senninha vai vencer o Rubinho? É o “Rubinho versus Senninha”. Além disso, tem a historinha “Férias na Fazenda”, com muitas brincadeiras. E tem mais: os amigos da turma fazem de tudo para colocar um ovo em pé e não conseguem. Será que eles vão desistir?', 36, '03/11/2015', 'https://dvygmnfdru1l.cloudfront.net/Uo4mMNdEzTLp2FyTnBC2/4/53d6a87a-6fd9-4099-a872-976daeffe532', 'Mauricio de Sousa', 30.00, '1');

-- Inserção dos dados da revista "Senninha e Sua Turma #5"
INSERT INTO comic (title, synopsis, page_count, date, image, creator, price, rarity) VALUES ('Senninha e Sua Turma #5', 'Senninha e seus amigos vão viajar para a praia. Lá eles vão fazer várias brincadeiras e aproveitar o sol e o mar. Mas nem tudo sai como planejado. Senninha fica com medo do mar e precisa superar seu medo. Será que ele vai conseguir? É a história “Senninha e o medo do mar”. Além disso, tem a historinha “O sorriso de vitória”, em que Senninha aprende a importância de ser persistente e não desistir dos seus sonhos.', 36, '03/11/2015', 'https://dvygmnfdru1l.cloudfront.net/Uo4mMNdEzTLp2FyTnBC2/5/53d6a87a-6fd9-4099-a872-976daeffe532', 'Mauricio de Sousa', 35.00, '1');

-- Inserção dos dados da revista "Senninha e Sua Turma #6"
INSERT INTO comic (title, synopsis, page_count, date, image, creator, price, rarity) VALUES ('Senninha e Sua Turma #6', 'Senninha e seus amigos estão em uma competição de kart. Eles vão se divertir muito acelerando seus karts na pista. Mas nem tudo são flores, eles vão enfrentar desafios e terão que mostrar habilidade e trabalho em equipe para vencer. É a história “A corrida de kart”. Além disso, tem a historinha “O mundo da lua”, em que Senninha viaja para a lua e vive uma aventura espacial.', 36, '03/11/2015', 'https://dvygmnfdru1l.cloudfront.net/Uo4mMNdEzTLp2FyTnBC2/6/53d6a87a-6fd9-4099-a872-976daeffe532', 'Mauricio de Sousa', 40.00, '1');

-- Inserção dos dados da revista "Senninha e Sua Turma #7"
INSERT INTO comic (title, synopsis, page_count, date, image, creator, price, rarity) VALUES ('Senninha e Sua Turma #7', 'Senninha e seus amigos vão fazer uma viagem de férias para a fazenda. Lá eles vão aprender sobre os animais, plantações e como cuidar da natureza. Eles também vão enfrentar desafios e viver aventuras no campo. É a história “Aventuras na fazenda”. Além disso, tem a historinha “O show de talentos”, em que Senninha e sua turma participam de um concurso de talentos.', 36, '03/11/2015', 'https://dvygmnfdru1l.cloudfront.net/Uo4mMNdEzTLp2FyTnBC2/7/53d6a87a-6fd9-4099-a872-976daeffe532', 'Mauricio de Sousa', 45.00 , '1');

-- Inserção dos dados da revista "Senninha e Sua Turma #8"
INSERT INTO comic (title, synopsis, page_count, date, image, creator, price, rarity) VALUES ('Senninha e Sua Turma #8', 'Senninha e seus amigos vão participar de um torneio de futebol. Eles vão treinar bastante para se preparar para os jogos e enfrentarão times de outras escolas. Além do futebol, também vão enfrentar desafios e aprender importantes lições sobre trabalho em equipe e superação. É a história “O torneio de futebol”. Além disso, tem a historinha “A máquina do tempo”, em que Senninha faz uma viagem no tempo e conhece personagens históricos.', 36, '03/11/2015', 'https://dvygmnfdru1l.cloudfront.net/Uo4mMNdEzTLp2FyTnBC2/8/53d6a87a-6fd9-4099-a872-976daeffe532', 'Mauricio de Sousa', 50.00 , '1');
